### ISSUE TITLE
send photo promise rejection

### ISSUE THREAD

**Issue by ni5am** [snlangsuan/line-messaging#4]
when send photo

`UnhandledPromiseRejectionWarning: Unhandled promise rejection`

**Comment by snlangsuan** [comment]
please send your code when call function send photo, Thank you.

**Comment by ni5am** [comment]
just call
bot.pushTextMessage('XXXXXXXX', body.menu.menu[i]);
bot.pushImageMessage('XXXXXXXXXX', body.menu.photos[i], body.menu.photos[i]+"?type=s480");

node --version  : v6.9.1

**Comment by snlangsuan** [comment]
Ok, I not found error on node version 4, but found on node version 6. 

I will fix it soon.

Current, You fix error:
bot.pushImageMessage('XXXXXXXXXX', body.menu.photos[i], body.menu.photos[i]+"?type=s480").catch(function(error) {
    console.error(error);
});

Thank you.

**Comment by ni5am** [comment]
thankyou very much!
