### ISSUE TITLE
description error

### ISSUE THREAD

**Issue by izumiogino** [snlangsuan/line-messaging#5]
'LINEBot.ActionType.POSTBACK' is not work.
The right way is 'LINEBot.Action.POSTBACK'

If I have a misunderstanding, please tell me.

**Comment by snlangsuan** [comment]
I so sorry... I forget update README.md

If you want to set action type to any action button, please use LINEbot.Action and follow with MESSAGE, POSTBACK or URI 

Thank you.

**Comment by izumiogino** [comment]
Thank you!
