### ISSUE TITLE
i hope have an uniform interface 

### ISSUE THREAD

**Issue by izumiogino** [snlangsuan/line-messaging#6]
If you can i hope this sdk have an uniform interface to handle message builder, like this:
let msgObj = {
     Type: 'text'
     Data: {
         Msg: 'this is message'
     }}
}}

Or

let msgObj = {
     Type: 'button'
     Data: {
         CommonMsg: 'this message show in PC',
         Title: 'this is title',
         Thumbnail: null,
         Msg: 'this message show in phone',
         Action: {
             [
                 Label: 'button text',
                 Data: 'send button text'
             ],
             [
                 Label: 'postback button',
                 Data: 'action = postback & content = 123',
                 Type: 'postback'
             ]
         }
     }
}

Then just use:

let msgBuilt = new LINEBot.messageBuiler (msgObj);

Bot.replyMessage (token, msgBuilt);

Do you think this is a good proposal?

what should i do?

**Comment by snlangsuan** [comment]
Hi izumiogino.

In "line-messaging" version 1.1.7, You can send message with JSON format 

sample code:
`let msgObj = {
    "to": <user id>,,
    "messages":[
        {
            "type":"text",
            "text":"Hello, world1"
        }
    ]
};`

Bot.pushJsonMessage(msgObj);

and when use reply message

`let msgObj = {
    "replyToken": <reply token>,
    "messages":[
        {
            "type":"text",
            "text":"Hello, user"
        }
    ]
};`

Bot.replyJsonMessage(msgObj);

Thank for you used.

**Comment by izumiogino** [comment]
thank you!
